name: FiveM Release

on:
  workflow_call:

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Escrow Version
        run: |
          mkdir ata_shop_escrow
          rsync -av --exclude='.git/' ./ ata_shop_escrow/
          zip -r ata_shop_escrow.zip ata_shop_escrow

      - name: Prepare Open Source Version
        run: |
          mkdir ata_shop_opensource
          rsync -av --exclude='.git/' ./ ata_shop_opensource/
          zip -r ata_shop_opensource.zip ata_shop_opensource

      - name: Generate Release Tag
        id: tag
        run: echo "release_tag=release-$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            ata_shop_escrow.zip
            ata_shop_opensource.zip
