name: FiveM Release
on:
  workflow_call:
permissions:
  contents: write
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Repository Name
        id: repo_name
        run: echo "repo_name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT
      - name: Get Version from fxmanifest
        id: get_version
        run: |
          VERSION=$(grep -E "version ['\"][0-9]+\.[0-9]+\.[0-9]+['\"]" fxmanifest.lua | sed -E "s/.*version ['\"]([0-9]+\.[0-9]+\.[0-9]+)['\"].*/\1/")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Prepare Escrow Version
        run: |
          # Create a folder with repository name
          mkdir -p ${{ steps.repo_name.outputs.repo_name }}
          # Copy files to that folder
          rsync -av --exclude='.git/' --exclude='.github/' --exclude='*.zip' ./ ${{ steps.repo_name.outputs.repo_name }}/
          # Create zip with the folder
          zip -r ${{ steps.repo_name.outputs.repo_name }}_${{ steps.get_version.outputs.version }}_escrow.zip ${{ steps.repo_name.outputs.repo_name }}
          # Clean up
          rm -rf ${{ steps.repo_name.outputs.repo_name }}
      - name: Prepare Open Source Version
        run: |
          # Create a folder with repository name
          mkdir -p ${{ steps.repo_name.outputs.repo_name }}
          # Copy files to that folder
          rsync -av --exclude='.git/' --exclude='.github/' --exclude='*.zip' ./ ${{ steps.repo_name.outputs.repo_name }}/
          # Create zip with the folder
          zip -r ${{ steps.repo_name.outputs.repo_name }}_${{ steps.get_version.outputs.version }}_opensource.zip ${{ steps.repo_name.outputs.repo_name }}
          # Clean up
          rm -rf ${{ steps.repo_name.outputs.repo_name }}
      - name: Generate Release Tag
        id: tag
        run: echo "release_tag=v${{ steps.get_version.outputs.version }}" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            ${{ steps.repo_name.outputs.repo_name }}_${{ steps.get_version.outputs.version }}_escrow.zip
            ${{ steps.repo_name.outputs.repo_name }}_${{ steps.get_version.outputs.version }}_opensource.zip
